#!/bin/sh
### BEGIN INIT INFO
# Provides:          firstboot_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition, and mark root ro
# Description:
### END INIT INFO
#    sed -i 's/defaults/defaults,ro/g' /etc/fstab &&
. /lib/lsb/init-functions

create_partition() {
    new_sector=$(($(echo p | fdisk /dev/mmcblk0| grep mmcblk0p2 | awk '{print $3}')+1))
    fdisk "/dev/mmcblk0" <<EOF || true
n
p
3
${new_sector}

w
EOF
}

case "$1" in
  start)
    if [ -e /dev/mmcblk0p3 ]; then
        mkfs.ext4 -F -F /dev/mmcblk0p3
        mount /dev/mmcblk0p3 /mnt
        cp -a /home/* /mnt/
        umount /mnt
        echo '/dev/mmcblk0p3  /home           ext4    defaults,noatime     0       3' >> /etc/fstab
        ROOT_DEV=$(findmnt / -o source -n)
        resize2fs $ROOT_DEV
        mount -oremount,rw /
        update-rc.d firstboot_once remove
        (systemctl disable firstboot_once || true)
        rm -f /etc/init.d/firstboot_once
    else
        create_partition
    fi
    echo "Rebooting"
    shutdown -r now
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
